apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gcp/frontend
images:
  - name: kuberag-web
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-web
    digest: sha256:c930f0fb73af06d55696d5a35c322583848c91cb99d5509f6bd45392f60f9e16
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberag-web
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
