apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gcp/frontend
images:
  - name: kuberag-web
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-web
    digest: sha256:0becad38ab9bfe196c2a283bbe64d0b258bd1d1859ec66b19a3e2356ebfb3d48
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberag-web
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
