apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gcp/frontend
images:
  - name: kuberag-web
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-web
    digest: sha256:0febcaed0d7607bfdb911278e689196a9f865f83ee77cc87f8e29aebff5cdeac
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberag-web
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
