k3s_version: "v1.35.5+k3s1"
k3s_sha256: "267d18da7b3c837d82283f0588fb9031a8a6ff3c0dac772c260c40852ce515f6"
k3s_api_host: "127.0.0.1"
k3s_kubeconfig_path: "{{ lookup('env', 'HOME') }}/.kube/kuberag-k3s.yaml"
k3s_disable_components:
  - traefik
k3s_node_labels:
  - "kuberag.io/topology=single-node"
  - "kuberag.io/role=all-in-one"
