resources:
  - ../../base/namespaces
  - ../../base/pss-smoke
  - ../../base/gateway
  - http-route-smoke.yaml

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: kuberag
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/listeners/0/port
        value: 8080
