apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/rag-api
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberag-rag-api
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: "false"
      - op: remove
        path: /spec/template/spec/containers/0/env/3
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: PUBLIC_DEMO_MODE
          value: "true"
