apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/prefect/ingest-run
images:
  - name: kuberag-ingestion
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-ingestion
    digest: sha256:5d42fbc2c72c7f62de36d6bcfee39b035c24c36b7266955cc52024a888df2658
patches:
  - target:
      group: batch
      version: v1
      kind: Job
      name: kuberag-ingest-run
      namespace: prefect
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
