apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gcp/rag-api
images:
  - name: kuberag-rag-api
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-api
    digest: sha256:6f830e78a1cab6841ea3cd10022606e333fc3e8daca0e4bf413434cbe1b01901
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberag-rag-api
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
