apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../gcp/rag-api
images:
  - name: kuberag-rag-api
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-api
    digest: sha256:3effa480d690775d75f7eaa251f585918378018253d15ceabafb64559cb3aa29
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kuberag-rag-api
      namespace: rag
    patch: |-
      - op: replace
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
