apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuberag-embedding-models
  namespace: prefect
  labels:
    app.kubernetes.io/name: kuberag-embedding-models
    app.kubernetes.io/part-of: kuberag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
