apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../postgresql-expand

patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: kuberag-pg
      namespace: data
    patch: |-
      - op: replace
        path: /spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms/0/matchExpressions/0/values
        value:
          - observability
          - application
