apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - llm-models-pvc.yaml
  - llm-model-warm-job.yaml
  - rag-api-embedding-pvc.yaml
  - rag-api-embedding-warm-job.yaml
  - prefect-embedding-pvc.yaml
  - prefect-embedding-warm-job.yaml

images:
  - name: kuberag-rag-api
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-api
    digest: sha256:677438c1e2e9278ca661801e4695ab263a684972d4f6bab12442366303c3e92b
  - name: kuberag-ingestion
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-ingestion
    digest: sha256:ca85d278ebe7c9190cb59b15fe787ffdc1eb3d465040b7cfbeddbbf2a37b2ec1
