apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - llm-models-pvc.yaml
  - llm-model-warm-job.yaml
  - rag-api-embedding-pvc.yaml
  - rag-api-embedding-warm-job.yaml
  - prefect-embedding-pvc.yaml
  - prefect-embedding-warm-job.yaml

images:
  - name: kuberag-rag-api
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-api
    digest: sha256:6f830e78a1cab6841ea3cd10022606e333fc3e8daca0e4bf413434cbe1b01901
  - name: kuberag-ingestion
    newName: asia-southeast1-docker.pkg.dev/kube-rag-platform/kuberag/kuberag-ingestion
    digest: sha256:5d42fbc2c72c7f62de36d6bcfee39b035c24c36b7266955cc52024a888df2658
