apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuberag-llm-models-application
  namespace: rag
  labels:
    app.kubernetes.io/name: kuberag-llm-models
    app.kubernetes.io/part-of: kuberag
    kuberag.io/role: application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
